require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

# Override Firebase SDK Version
$FirebaseSDKVersion = '7.8.1'

target 'HelloWorld' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'HelloWorldTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!({
  #   'Flipper' => '0.79.1'
  #   'Flipper-Folly' => '2.3.0'
  # })
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end

  # add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
  # add pods for any other desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods
end

target 'HelloWorld-tvOS' do
  # Pods for HelloWorld-tvOS

  target 'HelloWorld-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
